#!/bin/bash
thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ${thisdir}
parse_version='1.1.2'
jarfile=ixa-pipe-parse-$parse_version.jar

java -Xmx1000m -jar $jarfile parse -g sem -m parse-models/en-parser-chunking.bin
